# Generated by Django 5.2.2 on 2025-06-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('name', 'subject'), name='unique_student_subject', violation_error_message='Student already exists for this subject'),
        ),
    ]
